version: '3'

volumes:
  local-dbt-env-shell-history: # This basically let's docker auto-manage this volume.

services:
  local-dbt-env:
    profiles:
      - development
    platform: linux/amd64 # We force the platform for consistency.
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock # Forwards the local Docker socket to the container.
      - local-dbt-env-shell-history:/commandhistory # Volume that stores shell history between sessions

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/zsh -c "while sleep 1000; do :; done"
    env_file: devcontainer.env